# Generated by Django 3.0.8 on 2020-07-03 15:47

import QuestionViewerApp.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionViewerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.FileField(blank=True, upload_to='question', validators=[QuestionViewerApp.validator.validate_file_extension]),
        ),
    ]
